### ISSUE TITLE
cannot resolve module

### ISSUE THREAD

**Issue by samuelbirch** [ericclemmons/npm-install-webpack-plugin#35] opened 2016-03-17 16:21 UTC
I'm getting an issue where once the module has been installed, and the package.json updated, webpack then tries to do its thing, but cannot resolve the module, its looking in my app's source folder rather than the node_modules folder in the root of the project. As soon as i stop and restart webpack its fine.

Any ideas?

**Comment by ericclemmons** [comment] 2016-03-17 17:48
Duplicate of #34.

**Closed by ericclemmons** 2016-03-17 17:48 UTC
